import os

BOT_TOKEN: str = os.environ["BOT_TOKEN"]

SUPPORT_GROUP_ID: str = os.environ["SUPPORT_GROUP_ID"]

PROJECT_ROOT = os.environ["PROJECT_ROOT"]

TELEGRAM_PREMADE_COLORS_FOLDER_URL: str = os.environ["TELEGRAM_PREMADE_COLORS_FOLDER_URL"]

TELEGRAM_PREMADE_ICONS_FOLDER_URL: str = os.environ["TELEGRAM_PREMADE_ICONS_FOLDER_URL"]